import{i as a,S as m}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const u=document.querySelector(".form"),l=document.querySelector(".gallery"),f=document.querySelector(".loader");u.addEventListener("submit",d);function d(o){o.preventDefault(),l.innerHTML="";const r=o.target.elements.input.value;if(r.trim())g(r),o.currentTarget.reset();else return a.error({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#EF4040",position:"topLeft",timeout:2500})}f.classList.remove("is-hidden");function g(o){const r="https://pixabay.com",i="/api/",n=new URLSearchParams({key:"42189534-0458e72641624c0165f7139a5",q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=r+i+"?"+n;fetch(e,n).then(t=>t.json()).then(t=>{const s=t.hits;s.length===0&&h(),y(s),spanLoader.remove()}).catch(t=>{a.error({messageColor:"#FFF",color:"#EF4040",position:"topRight",message:`${t}`})}),hideLoader()}function h(){l.innerHTML="",a.error({messageColor:"#FFF",color:"#EF4040",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function y(o){const r=o.map(({largeImageURL:i,webformatURL:n,tags:e,likes:t,views:s,comments:c,downloads:p})=>`<li class='gallery-item'>
  <a class='gallery-link' href='${i}'>
    <img class='gallery-image' src='${n}' alt='${e}'/>
  </a>
<div class='container-app'>
<p><span>Likes</span> ${t}</p>
<p><span>Views</span> ${s}</p>
<p><span>Comments</span> ${c}</p>
<p><span>Downloads</span> ${p}</p>
</div>
 </li>`).join("");l.insertAdjacentHTML("afterBegin",r),L()}function L(){const o=new m(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});o.on("show.simpleLightbox"),o.refresh()}
//# sourceMappingURL=commonHelpers.js.map
